<?php require 'app/layouts/header.phtml'; ?>

<ul>
    <li><a href="/public/index.php?controller=index&action=index">Index</a></li>
    <li><a href="/public/index.php?controller=calculator&action=sum">Sum</a></li>
    <li><a href="/public/index.php?controller=calculator&action=subtract">Subtract</a></li>
    <li><a href="/public/index.php?controller=calculator&action=multiply">Multiply</a></li>
</ul>